"use client";

import Link from 'next/link';
import { ArrowRight, CalendarDays, CheckCircle2, MapPin, Target } from 'lucide-react';
import { festival2026 } from '@/lib/festival2026';
import { useAppStore } from '@/store/useAppStore';

const copy = {
  en: { eyebrow: '2026 India Pre-Selection', heading: 'Applications Are Closed', intro: 'The 2026 India Pre-Selection took place on 30 August 2026. New applications for this completed stage are no longer being accepted.', completed: 'India Pre-Selection: Completed', preserved: 'Historical submissions and review records remain preserved for existing applicants and the K-CUBE team.', updates: 'View Official Updates', info: 'Festival Information', next: 'What Happens Next', upcoming: 'Upcoming', main: 'Main Festival', datesNote: 'Current dates and participation updates should be followed through official K-CUBE announcements.', applicants: 'Existing Applicants', submitted: 'Already Submitted Your Application?', submittedText: 'If you submitted during the 2026 India Pre-Selection period, your application and review records remain available through your K-CUBE account. Continue following official announcements for selection and festival updates.', submission: 'View My Submission', account: 'My Account', announcements: 'Latest Announcements', shortlisted: 'Shortlisted Participants', active: 'Stay Active During the Final Evaluation Journey', activeText: 'Shortlisted participants awaiting final confirmation should continue following the latest K-CUBE participation guidance and official announcements.', target: 'Daily Activity Target', targetValue: '1,000+ Points', targetText: 'Earn eligible K-CUBE activity points through available platform activities and referral participation while awaiting final confirmation.', disclaimer: 'Activity points support participation engagement but do not guarantee final selection.', activities: 'Explore Activities', rewards: 'View Rewards', missed: 'Next Participation Cycle', missedHeading: 'Missed the 2026 India Pre-Selection?', missedText: 'The 2026 application period has ended. K-CUBE plans to share future India participation opportunities for the next ITAEWON World Music Spirit Festival cycle after official confirmation.', update2027: '2027 · Next Participation Update', requirements: 'Registration dates, eligibility and submission requirements will be announced through official K-CUBE channels.', follow: 'Follow K-CUBE Updates', context: 'ITAEWON World Music Spirit Festival', location: 'Seoul, South Korea', contextText: 'Learn more about the festival, its cultural purpose, India participation journey and official updates.', explore: 'Explore Festival Information' },
  ko: { eyebrow: '2026 인도 프리셀렉션', heading: '신청이 종료되었습니다', intro: '2026 인도 프리셀렉션은 2026년 8월 30일에 진행되었습니다. 완료된 단계에 대한 신규 신청은 더 이상 받지 않습니다.', completed: '인도 프리셀렉션: 완료', preserved: '기존 신청자와 K-CUBE 팀을 위해 과거 제출 자료와 검토 기록이 보존됩니다.', updates: '공식 업데이트 보기', info: '축제 정보', next: '다음 단계', upcoming: '예정', main: '메인 축제', datesNote: '현재 일정과 참가 업데이트는 K-CUBE 공식 공지를 확인하세요.', applicants: '기존 신청자', submitted: '이미 신청서를 제출하셨나요?', submittedText: '2026 인도 프리셀렉션 기간에 신청했다면 신청 및 검토 기록을 K-CUBE 계정에서 확인할 수 있습니다. 선발 및 축제 업데이트를 공식 공지에서 계속 확인하세요.', submission: '내 신청 보기', account: '내 계정', announcements: '최신 공지', shortlisted: '최종 후보 참가자', active: '최종 평가 여정 동안 계속 활동하세요', activeText: '최종 확인을 기다리는 최종 후보자는 최신 K-CUBE 참가 안내와 공식 공지를 계속 확인해야 합니다.', target: '일일 활동 목표', targetValue: '1,000+ 포인트', targetText: '최종 확인을 기다리는 동안 K-CUBE 활동과 추천 참여를 통해 적립 가능한 포인트를 획득하세요.', disclaimer: '활동 포인트는 참가 활동을 지원하지만 최종 선발을 보장하지 않습니다.', activities: '활동 둘러보기', rewards: '리워드 보기', missed: '다음 참가 주기', missedHeading: '2026 인도 프리셀렉션을 놓치셨나요?', missedText: '2026년 신청 기간은 종료되었습니다. K-CUBE는 공식 확인 후 다음 이태원 세계 음악 페스티벌 주기의 인도 참가 기회를 안내할 예정입니다.', update2027: '2027 · 다음 참가 업데이트', requirements: '등록 일정, 자격 요건과 제출 조건은 K-CUBE 공식 채널을 통해 안내됩니다.', follow: 'K-CUBE 업데이트 팔로우', context: '이태원 세계 음악 페스티벌', location: '대한민국 서울', contextText: '축제의 문화적 의미, 인도 참가 여정과 공식 업데이트를 알아보세요.', explore: '축제 정보 보기' },
  hi: { eyebrow: '2026 इंडिया प्री-सेलेक्शन', heading: 'आवेदन बंद हैं', intro: '2026 इंडिया प्री-सेलेक्शन 30 अगस्त 2026 को आयोजित हुआ। इस पूर्ण चरण के लिए नए आवेदन अब स्वीकार नहीं किए जा रहे हैं।', completed: 'इंडिया प्री-सेलेक्शन: पूरा हुआ', preserved: 'मौजूदा आवेदकों और K-CUBE टीम के लिए पुराने सबमिशन और समीक्षा रिकॉर्ड सुरक्षित हैं।', updates: 'आधिकारिक अपडेट देखें', info: 'फेस्टिवल की जानकारी', next: 'अगला चरण', upcoming: 'आगामी', main: 'मुख्य फेस्टिवल', datesNote: 'वर्तमान तारीखों और भागीदारी अपडेट के लिए K-CUBE की आधिकारिक घोषणाएँ देखें।', applicants: 'मौजूदा आवेदक', submitted: 'क्या आपने आवेदन जमा किया था?', submittedText: 'यदि आपने 2026 इंडिया प्री-सेलेक्शन के दौरान आवेदन किया था, तो आपका आवेदन और समीक्षा रिकॉर्ड K-CUBE अकाउंट में उपलब्ध रहेगा। चयन और फेस्टिवल अपडेट के लिए आधिकारिक घोषणाएँ देखते रहें।', submission: 'मेरा सबमिशन देखें', account: 'मेरा अकाउंट', announcements: 'नवीनतम घोषणाएँ', shortlisted: 'शॉर्टलिस्ट किए गए प्रतिभागी', active: 'अंतिम मूल्यांकन यात्रा के दौरान सक्रिय रहें', activeText: 'अंतिम पुष्टि की प्रतीक्षा कर रहे शॉर्टलिस्ट प्रतिभागियों को नवीनतम K-CUBE भागीदारी निर्देश और आधिकारिक घोषणाएँ देखते रहना चाहिए।', target: 'दैनिक गतिविधि लक्ष्य', targetValue: '1,000+ पॉइंट्स', targetText: 'अंतिम पुष्टि की प्रतीक्षा करते हुए उपलब्ध K-CUBE गतिविधियों और रेफरल भागीदारी से योग्य पॉइंट्स कमाएँ।', disclaimer: 'गतिविधि पॉइंट्स भागीदारी में मदद करते हैं, लेकिन अंतिम चयन की गारंटी नहीं देते।', activities: 'गतिविधियाँ देखें', rewards: 'रिवॉर्ड्स देखें', missed: 'अगला भागीदारी चक्र', missedHeading: '2026 इंडिया प्री-सेलेक्शन से चूक गए?', missedText: '2026 आवेदन अवधि समाप्त हो गई है। आधिकारिक पुष्टि के बाद K-CUBE अगले ITAEWON वर्ल्ड म्यूज़िक स्पिरिट फेस्टिवल चक्र के लिए भारत की भागीदारी के अवसर साझा करेगा।', update2027: '2027 · अगला भागीदारी अपडेट', requirements: 'रजिस्ट्रेशन तारीखें, पात्रता और सबमिशन आवश्यकताएँ K-CUBE के आधिकारिक चैनलों पर घोषित की जाएँगी।', follow: 'K-CUBE अपडेट्स फॉलो करें', context: 'ITAEWON वर्ल्ड म्यूज़िक स्पिरिट फेस्टिवल', location: 'सियोल, दक्षिण कोरिया', contextText: 'फेस्टिवल के सांस्कृतिक उद्देश्य, भारत की भागीदारी यात्रा और आधिकारिक अपडेट जानें।', explore: 'फेस्टिवल की जानकारी देखें' },
} as const;

const ButtonLink = ({ href, children, primary = false }: { href: string; children: React.ReactNode; primary?: boolean }) => <Link href={href} className={`kc-button ${primary ? 'kc-button-primary' : 'kc-button-secondary'} w-full justify-center sm:w-auto`}>{children}<ArrowRight className="h-4 w-4" /></Link>;

export default function IndiaPreSelectionApplyPage() {
  const language = useAppStore((state) => state.language);
  const t = copy[language];

  return <main className="bg-[#eef4f8] px-3 py-6 text-[#102a43] sm:px-4 sm:py-8 lg:px-10 lg:py-10"><div className="mx-auto max-w-[1320px] space-y-5">
    <section className="grid gap-5 lg:grid-cols-[1.1fr_0.9fr]"><article className="rounded-[24px] border border-[#cbd9ea] bg-white p-6 shadow-[0_14px_35px_rgba(15,55,95,0.08)] sm:p-8 lg:p-10"><p className="kc-eyebrow">{t.eyebrow}</p><h1 className="mt-3 text-3xl font-black tracking-tight sm:text-5xl">{t.heading}</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-[#526f8f] sm:text-base">{t.intro}</p><div className="mt-6 rounded-[16px] border border-[#b9d9d0] bg-[#effaf6] p-5"><p className="flex items-center gap-2 text-sm font-black text-[#19745d]"><CheckCircle2 className="h-5 w-5" />{t.completed}</p><p className="mt-2 text-sm leading-6 text-[#526f8f]">{t.preserved}</p></div><div className="mt-6 flex flex-col gap-3 sm:flex-row"><ButtonLink href="/india-pre-selection/announcement" primary>{t.updates}</ButtonLink><ButtonLink href="/india-pre-selection/information">{t.info}</ButtonLink></div></article>
      <aside className="rounded-[24px] border border-[#cbd9ea] bg-white p-6 shadow-[0_14px_35px_rgba(15,55,95,0.06)] sm:p-8"><p className="kc-eyebrow">{t.next}</p><div className="mt-5 space-y-3"><div className="rounded-[16px] border border-[#b9cdec] bg-[#eef4ff] p-5"><p className="text-xs font-black uppercase tracking-[0.16em] text-[#2457d6]">{t.upcoming}</p><h2 className="mt-3 text-lg font-black">{festival2026.officialSecondRound.title}</h2><p className="mt-2 flex items-center gap-2 text-sm text-[#526f8f]"><CalendarDays className="h-4 w-4" />30 September 2026</p></div><div className="rounded-[16px] border border-[#e5c56b] bg-[#fff8df] p-5"><p className="text-xs font-black uppercase tracking-[0.16em] text-[#9a6800]">{t.main}</p><h2 className="mt-3 text-lg font-black">{festival2026.mainFestival.title}</h2><p className="mt-2 flex items-center gap-2 text-sm text-[#526f8f]"><MapPin className="h-4 w-4" />4-6 October 2026 · Seoul, South Korea</p></div></div><p className="mt-5 text-xs leading-5 text-[#526f8f]">{t.datesNote}</p></aside></section>
    <section className="rounded-[24px] border border-[#cbd9ea] bg-white p-6 shadow-[0_10px_28px_rgba(15,55,95,0.05)] sm:p-8"><p className="kc-eyebrow">{t.applicants}</p><h2 className="mt-2 text-2xl font-black sm:text-3xl">{t.submitted}</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-[#526f8f]">{t.submittedText}</p><div className="mt-6 flex flex-col gap-3 sm:flex-row"><ButtonLink href="/dashboard" primary>{t.submission}</ButtonLink><ButtonLink href="/profile">{t.account}</ButtonLink><ButtonLink href="/india-pre-selection/announcement">{t.announcements}</ButtonLink></div></section>
    <section className="rounded-[24px] border border-[#b9cdec] bg-[#f7faff] p-6 sm:p-8"><div className="flex items-start gap-4"><div className="rounded-[14px] bg-[#e8f0ff] p-3 text-[#2457d6]"><Target className="h-6 w-6" /></div><div><p className="kc-eyebrow">{t.shortlisted}</p><h2 className="mt-2 text-2xl font-black sm:text-3xl">{t.active}</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-[#526f8f]">{t.activeText}</p></div></div><div className="mt-6 grid gap-4 lg:grid-cols-[240px_1fr]"><div className="rounded-[16px] border border-[#2457d6]/25 bg-white p-5"><p className="text-xs font-black uppercase tracking-[0.16em] text-[#2457d6]">{t.target}</p><p className="mt-3 text-3xl font-black">{t.targetValue}</p></div><div className="rounded-[16px] border border-[#d8e1ee] bg-white p-5"><p className="text-sm leading-7 text-[#526f8f]">{t.targetText}</p><p className="mt-3 text-xs leading-5 text-[#8290a3]">{t.disclaimer}</p></div></div><div className="mt-5 flex flex-col gap-3 sm:flex-row"><ButtonLink href="/activities">{t.activities}</ButtonLink><ButtonLink href="/rewards">{t.rewards}</ButtonLink><ButtonLink href="/india-pre-selection/announcement">{t.announcements}</ButtonLink></div></section>
    <section className="grid gap-5 rounded-[24px] border border-[#d9c4f0] bg-[#f7f1ff] p-6 sm:p-8 lg:grid-cols-[1fr_280px] lg:items-center"><div><p className="kc-eyebrow">{t.missed}</p><h2 className="mt-2 text-2xl font-black sm:text-3xl">{t.missedHeading}</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-[#526f8f]">{t.missedText}</p><p className="mt-3 text-xs leading-5 text-[#526f8f]">{t.requirements}</p><div className="mt-5 flex flex-col gap-3 sm:flex-row"><ButtonLink href="/india-pre-selection/announcement" primary>{t.follow}</ButtonLink><ButtonLink href="/india-pre-selection/announcement">{t.updates}</ButtonLink></div></div><div className="rounded-[18px] border border-[#d7b8ef] bg-white p-6 text-center"><p className="text-5xl font-black text-[#5c2a8d]">2027</p><p className="mt-2 text-xs font-black uppercase tracking-[0.16em] text-[#7b4da4]">{t.update2027}</p></div></section>
    <section className="flex flex-col gap-5 rounded-[20px] border border-[#cbd9ea] bg-white p-6 sm:flex-row sm:items-center sm:justify-between sm:p-7"><div><p className="text-xs font-black uppercase tracking-[0.18em] text-[#2457d6]">{t.context}</p><p className="mt-2 flex items-center gap-2 text-sm font-bold text-[#526f8f]"><MapPin className="h-4 w-4" />{t.location}</p><p className="mt-3 max-w-2xl text-sm leading-6 text-[#526f8f]">{t.contextText}</p></div><ButtonLink href="/india-pre-selection/information" primary>{t.explore}</ButtonLink></section>
  </div></main>;
}
