"use client";

import Image from 'next/image';
import Link from 'next/link';
import { ArrowDown, ArrowRight, Check, Mail, Sparkles } from 'lucide-react';
import { motion, useReducedMotion, useScroll, useTransform } from 'framer-motion';
import { useRef } from 'react';

const roles = [
  { number: '01', title: 'Event crew', short: 'Make the room come alive.', description: 'Help bring K-CUBE workshops, festivals, meetups and cultural programs to life.', areas: ['Event setup', 'Participant coordination', 'Guest assistance', 'On-ground support'], image: '/assets/k-cube-banner.png' },
  { number: '02', title: 'Content & creative', short: 'Turn culture into stories.', description: 'Create content around Korean culture, K-Food, learning, events and community stories.', areas: ['Social media', 'Photo / video', 'Design', 'Content support'], image: '/assets/korean shopping.png' },
  { number: '03', title: 'Operations', short: 'Keep the ecosystem moving.', description: 'Support coordination and daily execution across K-CUBE programs.', areas: ['Program coordination', 'Platform operations', 'Partner support', 'Internal coordination'], image: '/assets/kcube-india-preselection-competition.jpg' },
];
const workAreas = [['EVENTS', 'Gather people around memorable cultural moments.', '/assets/itaewon.jpg'], ['CONTENT', 'Shape the stories that introduce Korean culture.', '/assets/korean shopping.png'], ['LEARNING', 'Make language practice feel welcoming and useful.', '/assets/k-cube-banner.png'], ['K-FOOD', 'Connect discovery, recipes and everyday experiences.', '/assets/korean shopping.png'], ['COMMUNITY', 'Build participation that feels personal and open.', '/assets/kcube-india-preselection-cube.png'], ['OPERATIONS', 'Create the structure that lets good work scale.', '/assets/kcube-india-preselection-competition.jpg']];
const benefits = [['Build real experience', 'Work across cultural events, content and digital programs.'], ['Grow with Korean culture', 'Participate closely in Korean culture-led projects and experiences.'], ['Create an impact', 'Help shape experiences for the K-CUBE community.'], ['Earn recognition', 'Eligible contributions may connect with K-CUBE recognition programs where applicable.']];
const journey = [['01', 'Choose your role', 'Explore the opportunity that matches how you would like to contribute.'], ['02', 'Tell us about yourself', 'Share your experience, strengths and the kind of work you want to do.'], ['03', 'K-CUBE review', 'The team reviews your details and considers the best fit for the current need.'], ['04', 'Next-step communication', 'If there is a fit, the K-CUBE team will contact you with the next step.']];
const applicationHref = 'mailto:kcubeadm@gmail.com?subject=K-CUBE%20Manpower%20Application&body=Hello%20K-CUBE%20team,%0A%0ARole%20I%20am%20interested%20in:%0A%0AAbout%20me:%0A';
const reveal = { hidden: { opacity: 0, y: 28 }, visible: { opacity: 1, y: 0 } };
type Progress = ReturnType<typeof useScroll>['scrollYProgress'];

function RolePoster({ role, index, progress, reducedMotion }: { role: (typeof roles)[number]; index: number; progress: Progress; reducedMotion: boolean }) {
  const start = index / roles.length;
  const end = (index + 1) / roles.length;
  const opacity = useTransform(progress, [Math.max(0, start - .16), start, end, Math.min(1, end + .16)], [.2, 1, 1, .2]);
  const scale = useTransform(progress, [Math.max(0, start - .16), start, end, Math.min(1, end + .16)], [.95, 1, 1, .95]);
  const y = useTransform(progress, [Math.max(0, start - .16), start, end, Math.min(1, end + .16)], [34, 0, 0, -34]);
  return <motion.article style={{ opacity: reducedMotion ? 1 : opacity, scale: reducedMotion ? 1 : scale, y: reducedMotion ? 0 : y }} className="overflow-hidden rounded-[26px] bg-white shadow-[0_24px_70px_rgba(16,42,67,.16)] lg:absolute lg:inset-0 lg:grid lg:grid-cols-[.92fr_1.08fr]"><div className="relative min-h-60 overflow-hidden bg-[#082b61] lg:min-h-0"><Image src={role.image} alt="" fill sizes="(max-width: 1024px) 100vw, 42vw" className="object-cover opacity-90" /><div className="absolute inset-0 bg-gradient-to-t from-[#082b61]/80 via-transparent to-transparent" /><span className="absolute bottom-5 left-6 text-7xl font-black text-white/85">{role.number}</span></div><div className="flex flex-col justify-center p-7 sm:p-10"><p className="kc-eyebrow">Role {role.number}</p><h3 className="mt-3 text-4xl font-black tracking-tight text-[#0b2850] sm:text-5xl">{role.title}</h3><p className="mt-3 text-xl font-bold text-[#1460c2]">{role.short}</p><p className="mt-5 leading-7 text-[#486581]">{role.description}</p><ul className="mt-6 grid gap-2 text-sm font-bold text-[#284e75] sm:grid-cols-2">{role.areas.map((area) => <li key={area} className="flex items-center gap-2"><Check className="h-4 w-4 text-[#1460c2]" />{area}</li>)}</ul><a href={applicationHref} className="mt-8 inline-flex w-fit items-center gap-2 font-black text-[#1460c2] hover:text-[#082b61]">Apply for {role.title} <ArrowRight className="h-4 w-4" /></a></div></motion.article>;
}

export default function ManpowerPage() {
  const reducedMotion = useReducedMotion() ?? false;
  const heroRef = useRef<HTMLElement>(null);
  const rolesRef = useRef<HTMLElement>(null);
  const journeyRef = useRef<HTMLElement>(null);
  const { scrollYProgress: heroProgress } = useScroll({ target: heroRef, offset: ['start start', 'end start'] });
  const { scrollYProgress: rolesProgress } = useScroll({ target: rolesRef, offset: ['start start', 'end end'] });
  const { scrollYProgress: journeyProgress } = useScroll({ target: journeyRef, offset: ['start end', 'end start'] });
  const heroY = useTransform(heroProgress, [0, 1], ['0%', '8%']);
  const heroScale = useTransform(heroProgress, [0, 1], [1.03, 1.07]);
  const journeyLine = useTransform(journeyProgress, [.18, .78], ['0%', '100%']);
  return <div className="overflow-hidden bg-[#f1f6fb] text-[#102a43]">
    <section ref={heroRef} className="relative isolate min-h-[calc(100vh-126px)] overflow-hidden bg-[#082b61] text-white"><motion.div style={{ y: reducedMotion ? 0 : heroY, scale: reducedMotion ? 1 : heroScale }} className="absolute inset-0 -z-20 bg-[url('/assets/kcube-india-preselection-cube.png')] bg-cover bg-center opacity-75" aria-hidden="true" /><div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(5,31,72,.98)_0%,rgba(5,31,72,.86)_35%,rgba(5,31,72,.22)_78%),linear-gradient(0deg,rgba(5,31,72,.64),transparent_60%)]" /><motion.div style={{ y: reducedMotion ? 0 : heroY }} className="absolute right-[8%] top-[17%] -z-10 hidden h-56 w-56 rotate-12 rounded-[42px] border border-white/25 bg-white/10 lg:block" aria-hidden="true" /><div className="mx-auto flex min-h-[calc(100vh-126px)] max-w-[1480px] items-end px-6 pb-20 pt-24 sm:px-10 lg:px-16 lg:pb-28"><div className="max-w-4xl"><motion.div initial={reducedMotion ? false : 'hidden'} animate={reducedMotion ? undefined : 'visible'} variants={{ hidden: { opacity: 0, y: 18 }, visible: { opacity: 1, y: 0 } }} transition={{ duration: .7 }}><p className="mb-7 flex items-center gap-3 text-xs font-black uppercase tracking-[.28em] text-[#ffc400]"><Sparkles className="h-4 w-4" /> K-CUBE MANPOWER</p><h1 className="max-w-4xl text-5xl font-black leading-[.94] tracking-[-.055em] sm:text-7xl lg:text-[clamp(5rem,8.5vw,9rem)]"><span className="block">Build</span><span className="block">Korea&apos;s</span><span className="block">culture</span><span className="block">ecosystem</span><span className="block">with us.</span></h1><p className="mt-8 max-w-2xl text-lg leading-8 text-[#e0edfb] sm:text-xl">Join the people behind K-CUBE events, Korean culture content, learning, community programs and operations.</p><div className="mt-10 flex flex-wrap gap-4"><a href="#roles" className="inline-flex items-center gap-3 rounded-full bg-[#1460c2] px-6 py-3.5 font-black text-white transition hover:bg-[#1d73df]">Explore opportunities <ArrowDown className="h-4 w-4" /></a><a href={applicationHref} className="inline-flex items-center gap-3 rounded-full border border-white/55 px-6 py-3.5 font-black text-white transition hover:bg-white hover:text-[#082b61]">Apply now <ArrowRight className="h-4 w-4" /></a></div></motion.div></div></div></section>
    <motion.section initial={reducedMotion ? false : 'hidden'} whileInView={reducedMotion ? undefined : 'visible'} viewport={{ once: true, amount: .3 }} variants={reveal} transition={{ duration: .7 }} className="mx-auto max-w-[1480px] px-6 py-24 sm:px-10 lg:px-16 lg:py-36"><p className="kc-eyebrow">Work with K-CUBE</p><h2 className="mt-6 max-w-5xl text-5xl font-black leading-[.96] tracking-[-.045em] text-[#0b2850] sm:text-7xl">Culture is built by people.</h2><div className="mt-10 grid gap-8 lg:grid-cols-2 lg:gap-24"><p className="text-xl leading-9 text-[#365b80]">K-CUBE brings together Korean culture, events, learning, food, community experiences and digital participation.</p><p className="text-xl leading-9 text-[#365b80]">Behind every experience is a team that makes it happen. Bring your perspective, your craft and your energy to the ecosystem.</p></div></motion.section>
    <section ref={rolesRef} id="roles" className="relative bg-[#e3eefb] lg:min-h-[175vh]"><div className="mx-auto max-w-[1480px] px-6 py-20 sm:px-10 lg:sticky lg:top-[126px] lg:flex lg:h-[calc(100vh-126px)] lg:items-center lg:gap-14 lg:px-16 lg:py-10"><div className="max-w-md shrink-0 lg:w-[35%]"><p className="kc-eyebrow">Explore roles</p><h2 className="mt-5 text-5xl font-black leading-[.98] tracking-[-.045em] text-[#0b2850] sm:text-6xl">Find your place inside K-CUBE.</h2><p className="mt-6 text-lg leading-8 text-[#486581]">Scroll to explore opportunities.</p><div className="mt-9 hidden h-1 w-40 overflow-hidden bg-[#c8d8eb] lg:block"><motion.div style={{ scaleX: reducedMotion ? 1 : rolesProgress }} className="h-full origin-left bg-[#1460c2]" /></div></div><div className="mt-12 grid gap-5 lg:relative lg:mt-0 lg:h-[min(600px,70vh)] lg:flex-1">{roles.map((role, index) => <RolePoster key={role.number} role={role} index={index} progress={rolesProgress} reducedMotion={reducedMotion} />)}</div></div></section>
    <section className="bg-[#082b61] py-24 text-white sm:py-32"><div className="mx-auto max-w-[1480px] px-6 sm:px-10 lg:px-16"><p className="text-xs font-black uppercase tracking-[.28em] text-[#ffc400]">What you could work on</p><div className="mt-6 grid gap-12 lg:grid-cols-[.8fr_1.2fr] lg:items-end"><h2 className="max-w-3xl text-5xl font-black leading-[.95] tracking-[-.045em] sm:text-7xl">Work behind real experiences.</h2><p className="max-w-xl text-lg leading-8 text-[#c9dcf3]">From the first idea to the moment a community gathers, every layer of K-CUBE needs thoughtful people.</p></div><div className="mt-16 grid gap-5 md:grid-cols-2 lg:grid-cols-3"><div className="relative min-h-[380px] overflow-hidden md:col-span-2 lg:row-span-2"><Image src="/assets/itaewon.jpg" alt="K-CUBE cultural event artwork" fill sizes="(max-width: 1024px) 100vw, 55vw" className="object-cover transition-transform duration-700 hover:scale-105" /><div className="absolute inset-0 bg-gradient-to-t from-[#051f48] via-transparent to-transparent" /><p className="absolute bottom-6 left-6 text-3xl font-black">Culture in motion.</p></div>{workAreas.slice(1, 5).map(([title, text, image], index) => <motion.div key={title} initial={reducedMotion ? false : 'hidden'} whileInView={reducedMotion ? undefined : 'visible'} viewport={{ once: true, amount: .35 }} variants={reveal} transition={{ duration: .5, delay: index * .05 }} className="group relative min-h-44 overflow-hidden border border-white/20 p-5"><Image src={image} alt="" fill sizes="(max-width: 768px) 100vw, 25vw" className="object-cover opacity-25 transition duration-700 group-hover:scale-105 group-hover:opacity-40" /><div className="relative"><p className="text-sm font-black tracking-[.24em] text-[#ffc400]">{title}</p><p className="mt-4 max-w-xs text-lg leading-7 text-[#e0edfb]">{text}</p></div></motion.div>)}</div></div></section>
    <section className="mx-auto max-w-[1480px] px-6 py-24 sm:px-10 lg:px-16 lg:py-36"><p className="kc-eyebrow">Why join K-CUBE</p><h2 className="mt-6 max-w-3xl text-5xl font-black leading-[.98] tracking-[-.045em] text-[#0b2850] sm:text-7xl">Bring your point of view.</h2><div className="mt-16 grid gap-x-16 gap-y-14 sm:grid-cols-2">{benefits.map(([title, text], index) => <motion.article key={title} initial={reducedMotion ? false : 'hidden'} whileInView={reducedMotion ? undefined : 'visible'} viewport={{ once: true, amount: .35 }} variants={reveal} transition={{ duration: .6, delay: index * .08 }} className={index % 2 ? 'sm:mt-16' : ''}><p className="text-sm font-black text-[#1460c2]">0{index + 1}</p><h3 className="mt-4 text-3xl font-black text-[#0b2850]">{title}</h3><p className="mt-4 max-w-md text-lg leading-8 text-[#486581]">{text}</p></motion.article>)}</div></section>
    <section ref={journeyRef} className="bg-white px-6 py-24 sm:px-10 lg:px-16 lg:py-36"><div className="mx-auto grid max-w-[1480px] gap-14 lg:grid-cols-[.8fr_1.2fr]"><div className="lg:sticky lg:top-44 lg:h-fit"><p className="kc-eyebrow">Application journey</p><h2 className="mt-6 max-w-md text-5xl font-black leading-[.98] tracking-[-.045em] text-[#0b2850] sm:text-6xl">Your journey into K-CUBE.</h2><p className="mt-6 max-w-md text-lg leading-8 text-[#486581]">A clear conversation about where your skills can contribute. No automatic acceptance is promised.</p></div><div className="relative"><div className="absolute bottom-7 left-[21px] top-7 w-px bg-[#d8e4f0]" /><motion.div style={{ height: reducedMotion ? '100%' : journeyLine }} className="absolute left-[20px] top-7 w-0.5 origin-top bg-[#1460c2]" />{journey.map(([number, title, text]) => <div key={number} className="relative flex gap-7 pb-14 last:pb-0"><span className="z-10 flex h-11 w-11 shrink-0 items-center justify-center rounded-full border-2 border-[#1460c2] bg-white text-sm font-black text-[#1460c2]">{number}</span><div><h3 className="text-3xl font-black text-[#0b2850]">{title}</h3><p className="mt-3 max-w-lg text-lg leading-8 text-[#486581]">{text}</p></div></div>)}</div></div></section>
    <section id="application" className="relative overflow-hidden bg-[#1460c2] px-6 py-24 text-white sm:px-10 lg:px-16 lg:py-36"><div className="absolute inset-0 bg-[url('/assets/k-cube-banner.png')] bg-cover bg-center opacity-20" /><div className="absolute inset-0 bg-gradient-to-r from-[#1460c2]/90 to-[#1460c2]/45" /><div className="relative mx-auto max-w-[1480px]"><p className="text-xs font-black uppercase tracking-[.28em] text-[#ffc400]">Start the conversation</p><h2 className="mt-6 max-w-4xl text-5xl font-black leading-[.95] tracking-[-.05em] sm:text-7xl">Ready to build with K-CUBE?</h2><p className="mt-8 max-w-2xl text-xl leading-8 text-white/90">Choose the opportunity that fits you and tell us how you&apos;d like to contribute.</p><div className="mt-10 flex flex-wrap gap-4"><a href={applicationHref} className="inline-flex items-center gap-3 rounded-full bg-white px-6 py-3.5 font-black text-[#082b61] transition hover:bg-[#ffc400]">Apply to K-CUBE <Mail className="h-4 w-4" /></a><Link href="/about" className="inline-flex items-center gap-3 rounded-full border border-white/65 px-6 py-3.5 font-black transition hover:bg-white hover:text-[#082b61]">Explore K-CUBE <ArrowRight className="h-4 w-4" /></Link></div><p className="mt-6 text-sm text-white/80">For role applications, email the K-CUBE team with your preferred role and a short introduction.</p></div></section>
  </div>;
}
