"use client";

import Link from 'next/link';
import { ArrowRight, BellRing, Camera, CheckCircle2 } from 'lucide-react';
import { useAppStore, type Language } from '@/store/useAppStore';

type Copy = { notice:string; title:string; subtitle:string; intro:string; closed:string; ongoing:string; latest:string; info:string; status:string; latestTitle:string; latestText:string[]; existing:string; existingTitle:string; existingText:string; actions:[string,string,string][]; dates:string; datesTitle:string; selection:string; selectionTitle:string; progress:[string,string,string,string][]; next:string; nextTitle:string; nextText:string; stay:string; stayTitle:string; stayText:string; infoButton:string; follow:string };

const copy: Record<Language, Copy> = {
  en: { notice:'Official notice board · 2026', title:'ITAEWON World Music Spirit 2026', subtitle:'Official Announcements', intro:'Official updates for K-CUBE India participants, selection stages, important dates and festival-related notices.', closed:'India pre-selection · Closed', ongoing:'Selection process continues for existing participants.', latest:'View latest update', info:'Festival information', status:'Current status · Selection process ongoing', latestTitle:'India Pre-Selection Completed - Selection Process Continues', latestText:['The 2026 K-CUBE India Pre-Selection held on 30 August 2026 has now concluded.','Thank you to everyone who participated and submitted their performances.','Applications are now closed. Existing participant submissions remain part of the ongoing selection process.','Continue following official K-CUBE announcements for selection updates and upcoming stages.'], existing:'For existing participants', existingTitle:'What Should I Do Now?', existingText:'The application window is closed, but current participants should keep their account active and follow the operational updates below.', actions:[['01','Stay Active on K-CUBE','Continue using your K-CUBE account and follow your participant progress.'],['02','Final Selection Point Award','1,000 points are awarded after passing the final selection.'],['03','Watch Official Announcements','Selection-related updates and instructions will be published on this Announcement page.']], dates:'Important dates', datesTitle:'The next moments in the 2026 cycle', selection:'Selection status', selectionTitle:'2026 Selection Progress', progress:[['01','Applications','CLOSED','Applications are no longer being accepted.'],['02','India Pre-Selection','COMPLETED','30 August 2026'],['03','Selection / Review Process','CURRENT STAGE','Existing participant submissions remain relevant.'],['04','Official Second Round','UPCOMING','30 September 2026'],['05','Festival Stage','4–6 OCTOBER 2026','Seoul, Korea']], next:'Next participation cycle', nextTitle:'Interested in Participating Next Time?', nextText:'The 2026 India participation window has closed. Future opportunities for the next festival cycle will be announced after official confirmation.', stay:'Stay informed', stayTitle:'Follow the Official Festival Journey', stayText:'Keep checking K-CUBE for selection updates, participant instructions and official festival announcements.', infoButton:'View festival information', follow:'Follow K-CUBE updates' },
  ko: { notice:'공식 공지 게시판 · 2026', title:'이태원 세계 음악 스피릿 페스티벌 2026', subtitle:'공식 공지사항', intro:'K-CUBE 인도 참가자를 위한 공식 업데이트, 선발 단계, 주요 일정과 축제 안내입니다.', closed:'인도 프리셀렉션 · 종료', ongoing:'기존 참가자의 선발 과정은 계속 진행됩니다.', latest:'최신 업데이트 보기', info:'축제 정보', status:'현재 상태 · 선발 과정 진행 중', latestTitle:'인도 프리셀렉션 완료 - 선발 과정 진행 중', latestText:['2026년 8월 30일 진행된 K-CUBE 인도 프리셀렉션이 종료되었습니다.','참여하고 공연을 제출해 주신 모든 분께 감사드립니다.','신청은 종료되었습니다. 기존 참가자의 제출 자료는 선발 과정에서 계속 검토됩니다.','선발 업데이트와 다음 단계는 K-CUBE 공식 공지를 계속 확인해 주세요.'], existing:'기존 참가자', existingTitle:'이제 무엇을 해야 하나요?', existingText:'신청 기간은 종료되었지만 기존 참가자는 계정을 활성 상태로 유지하고 아래 안내를 확인해 주세요.', actions:[['01','K-CUBE에서 활동 유지','K-CUBE 계정을 계속 사용하며 참가자 진행 상황을 확인하세요.'],['02','최종 선발 포인트 보상','최종 선발에 통과한 후 1,000 포인트가 지급됩니다.'],['03','공식 공지 확인','선발 관련 업데이트와 안내는 이 공지 페이지에 게시됩니다.']], dates:'주요 일정', datesTitle:'2026년 다음 일정', selection:'선발 상태', selectionTitle:'2026년 선발 진행 상황', progress:[['01','신청','종료','신규 신청은 더 이상 받지 않습니다.'],['02','인도 프리셀렉션','완료','2026년 8월 30일'],['03','선발 / 검토 과정','현재 단계','기존 참가자의 제출 자료가 유효합니다.'],['04','공식 2차 라운드','예정','2026년 9월 30일'],['05','페스티벌 무대','2026년 10월 4–6일','대한민국 서울']], next:'다음 참가 주기', nextTitle:'다음 기회에 인도를 대표하고 싶으신가요?', nextText:'2026년 인도 참가 기간은 종료되었습니다. 다음 페스티벌 주기의 참가 기회는 공식 확인 후 안내됩니다.', stay:'계속 확인하기', stayTitle:'공식 페스티벌 여정을 확인하세요', stayText:'선발 업데이트, 참가자 안내와 공식 페스티벌 공지를 K-CUBE에서 계속 확인해 주세요.', infoButton:'페스티벌 정보 보기', follow:'K-CUBE 업데이트 팔로우' },
  hi: { notice:'आधिकारिक सूचना बोर्ड · 2026', title:'इटावॉन वर्ल्ड म्यूज़िक स्पिरिट फेस्टिवल 2026', subtitle:'आधिकारिक घोषणाएँ', intro:'K-CUBE इंडिया प्रतिभागियों के लिए आधिकारिक अपडेट, चयन चरण, महत्वपूर्ण तारीखें और फेस्टिवल जानकारी।', closed:'इंडिया प्री-सेलेक्शन · बंद', ongoing:'मौजूदा प्रतिभागियों की चयन प्रक्रिया जारी है।', latest:'नवीनतम अपडेट देखें', info:'फेस्टिवल की जानकारी', status:'वर्तमान स्थिति · चयन प्रक्रिया जारी', latestTitle:'इंडिया प्री-सेलेक्शन पूरा - चयन प्रक्रिया जारी', latestText:['30 अगस्त 2026 को हुआ 2026 K-CUBE इंडिया प्री-सेलेक्शन पूरा हो गया है।','भाग लेने और अपना प्रदर्शन जमा करने वाले सभी लोगों का धन्यवाद।','आवेदन बंद हैं। मौजूदा प्रतिभागियों के सबमिशन चयन प्रक्रिया में समीक्षा के लिए बने रहेंगे।','चयन अपडेट और अगले चरणों के लिए K-CUBE की आधिकारिक घोषणाएँ देखते रहें।'], existing:'मौजूदा प्रतिभागियों के लिए', existingTitle:'अब मुझे क्या करना चाहिए?', existingText:'आवेदन विंडो बंद है, लेकिन मौजूदा प्रतिभागियों को अपना अकाउंट सक्रिय रखना चाहिए और नीचे दिए अपडेट देखते रहना चाहिए।', actions:[['01','K-CUBE पर सक्रिय रहें','अपने K-CUBE अकाउंट का उपयोग जारी रखें और प्रतिभागी प्रगति देखें।'],['02','फाइनल चयन पॉइंट पुरस्कार','फाइनल चयन पास करने के बाद 1,000 पॉइंट्स दिए जाते हैं।'],['03','आधिकारिक घोषणाएँ देखें','चयन से जुड़े अपडेट और निर्देश इस घोषणा पेज पर प्रकाशित होंगे।']], dates:'महत्वपूर्ण तारीखें', datesTitle:'2026 चक्र के अगले चरण', selection:'चयन स्थिति', selectionTitle:'2026 चयन प्रगति', progress:[['01','आवेदन','बंद','नए आवेदन अब स्वीकार नहीं किए जा रहे हैं।'],['02','इंडिया प्री-सेलेक्शन','पूरा हुआ','30 अगस्त 2026'],['03','चयन / समीक्षा प्रक्रिया','वर्तमान चरण','मौजूदा प्रतिभागियों के सबमिशन प्रासंगिक हैं।'],['04','आधिकारिक दूसरा राउंड','आगामी','30 सितंबर 2026'],['05','फेस्टिवल चरण','4–6 अक्टूबर 2026','सियोल, दक्षिण कोरिया']], next:'अगला भागीदारी चक्र', nextTitle:'अगली बार भारत का प्रतिनिधित्व करना चाहते हैं?', nextText:'2026 भारत भागीदारी अवधि समाप्त हो गई है। अगले फेस्टिवल चक्र के अवसर आधिकारिक पुष्टि के बाद घोषित किए जाएंगे।', stay:'जानकारी लेते रहें', stayTitle:'आधिकारिक फेस्टिवल यात्रा से जुड़े रहें', stayText:'चयन अपडेट, प्रतिभागी निर्देश और आधिकारिक फेस्टिवल घोषणाओं के लिए K-CUBE देखते रहें।', infoButton:'फेस्टिवल की जानकारी देखें', follow:'K-CUBE अपडेट्स फॉलो करें' },
};

const Section = ({ children }: { children: React.ReactNode }) => <section className="px-3 pb-6 sm:px-4 lg:px-10"><div className="mx-auto max-w-[1240px] rounded-[24px] border border-[#cbd9ea] bg-white p-6 shadow-[0_10px_28px_rgba(15,55,95,0.05)] sm:p-8">{children}</div></section>;
const Eyebrow = ({ children }: { children: React.ReactNode }) => <p className="text-[11px] font-black uppercase tracking-[0.22em] text-[#b77900]">{children}</p>;

export default function AnnouncementPage() {
  const language = useAppStore((state) => state.language);
  const t = copy[language];
  return <main className="bg-[#eef4f8] py-6 text-[#102a43] sm:py-8">
    <section className="px-3 pb-6 sm:px-4 lg:px-10"><div className="mx-auto grid max-w-[1240px] gap-5 lg:grid-cols-[1fr_280px]"><article className="rounded-[24px] border border-[#cbd9ea] bg-white p-6 sm:p-9"><p className="inline-flex items-center gap-2 rounded-full border border-[#e5c56b] bg-[#fff8df] px-4 py-2 text-[10px] font-black uppercase tracking-[0.2em] text-[#9a6800]"><BellRing className="h-4 w-4" />{t.notice}</p><h1 className="mt-5 text-3xl font-black leading-tight sm:text-5xl">{t.title}<br />{t.subtitle}</h1><p className="mt-4 max-w-2xl text-sm leading-7 text-[#526f8f]">{t.intro}</p><div className="mt-5 flex flex-wrap items-center gap-3"><span className="inline-flex items-center rounded-full border border-[#b9d9d0] bg-[#effaf6] px-3 py-1.5 text-[10px] font-black uppercase text-[#19745d]"><CheckCircle2 className="mr-2 h-4 w-4" />{t.closed}</span><span className="text-sm font-semibold text-[#526f8f]">{t.ongoing}</span></div><div className="mt-6 flex flex-wrap gap-3"><a href="#latest-update" className="kc-button kc-button-primary">{t.latest}<ArrowRight className="h-4 w-4" /></a><Link href="/india-pre-selection/information" className="kc-button kc-button-secondary">{t.info}<ArrowRight className="h-4 w-4" /></Link></div></article><aside className="rounded-[24px] bg-[#102a43] p-6 text-white sm:p-7"><Eyebrow>{t.status}</Eyebrow><p className="mt-5 text-3xl font-black leading-tight">{t.status}</p><p className="mt-10 border-t border-white/20 pt-4 text-xs text-[#c3d8f1]">{t.latest} · {t.latestTitle}</p></aside></div></section>
    <div id="latest-update"><Section><Eyebrow>{t.latest}</Eyebrow><h2 className="mt-2 text-2xl font-black sm:text-3xl">{t.latestTitle}</h2><div className="mt-6 max-w-3xl space-y-4 text-sm leading-7 text-[#526f8f]">{t.latestText.map((text) => <p key={text}>{text}</p>)}</div></Section></div>
    <Section><Eyebrow>{t.existing}</Eyebrow><h2 className="mt-2 text-2xl font-black sm:text-3xl">{t.existingTitle}</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-[#526f8f]">{t.existingText}</p><div className="mt-6 grid gap-4 lg:grid-cols-3">{t.actions.map(([number,title,text], index) => <article key={title} className={`rounded-[18px] border p-5 ${index === 1 ? 'border-[#e5c56b] bg-[#fffdf5]' : 'border-[#d8e1ee] bg-[#f8fbff]'}`}><span className="text-xs font-black text-[#2457d6]">{number}</span><h3 className="mt-5 text-lg font-black">{title}</h3><p className="mt-3 text-sm leading-7 text-[#526f8f]">{text}</p></article>)}</div></Section>
    <Section><Eyebrow>{t.dates}</Eyebrow><h2 className="mt-2 text-2xl font-black sm:text-3xl">{t.datesTitle}</h2><div className="mt-6 grid gap-4 lg:grid-cols-3">{t.progress.slice(1,4).map(([number,title,status,detail]) => <article key={number} className="rounded-[18px] border border-[#d8e1ee] bg-[#f8fbff] p-5"><p className="text-xs font-black uppercase tracking-[0.16em] text-[#2457d6]">{status}</p><p className="mt-4 text-2xl font-black">{detail}</p><h3 className="mt-2 text-base font-black">{title}</h3></article>)}</div></Section>
    <Section><Eyebrow>{t.selection}</Eyebrow><h2 className="mt-2 text-2xl font-black sm:text-3xl">{t.selectionTitle}</h2><div className="mt-6 grid gap-3 md:grid-cols-5">{t.progress.map(([number,title,status,detail]) => <article key={number} className="rounded-[18px] border border-[#d8e1ee] bg-[#f8fbff] p-4"><span className="text-xs font-black text-[#2457d6]">{number}</span><h3 className="mt-4 text-sm font-black">{title}</h3><p className="mt-2 text-[10px] font-black uppercase text-[#b77900]">{status}</p><p className="mt-2 text-xs leading-5 text-[#526f8f]">{detail}</p></article>)}</div></Section>
    <Section><div className="grid gap-5 bg-[#f7f1ff] p-5 sm:grid-cols-[1fr_auto] sm:items-center"><div><Eyebrow>{t.next}</Eyebrow><h2 className="mt-2 text-2xl font-black">{t.nextTitle}</h2><p className="mt-3 max-w-3xl text-sm leading-7 text-[#526f8f]">{t.nextText}</p></div><Link href="/india-pre-selection/information" className="kc-button kc-button-primary">{t.infoButton}<ArrowRight className="h-4 w-4" /></Link></div></Section>
    <section className="px-3 pb-2 sm:px-4 lg:px-10"><div className="mx-auto grid max-w-[1240px] gap-5 rounded-[24px] bg-[#082f68] p-6 text-white sm:p-8 sm:grid-cols-[1fr_auto] sm:items-center"><div><Eyebrow>{t.stay}</Eyebrow><h2 className="mt-2 text-2xl font-black sm:text-3xl">{t.stayTitle}</h2><p className="mt-3 text-sm leading-7 text-[#d5e5fb]">{t.stayText}</p></div><div className="flex flex-wrap gap-3"><Link href="/india-pre-selection/information" className="kc-button kc-button-primary">{t.infoButton}<ArrowRight className="h-4 w-4" /></Link><a href="https://www.instagram.com/k_cube_store/" target="_blank" rel="noreferrer" className="kc-button kc-button-secondary"><Camera className="h-4 w-4" />{t.follow}</a></div></div></section>
  </main>;
}
