import type { Language } from '@/store/useAppStore';

export const memberUiCopy: Record<Language, Record<string, string>> = {
  en: {
    memberCommand: 'Member command center', dashboardHeading: 'Earn points from culture, learning, food and purchases.', dashboardIntro: 'K-CUBE tracks every meaningful action toward the Korea trip leaderboard. Upload your Korean culture content, complete daily learning, refer friends, and claim K-Food purchases.',
    ranking: 'Korea trip ranking', rankingDesc: 'Winner announcements are preceded by admin verification of uploads, learning, K-Food and manual adjustments.', visitShop: 'Visit K-CUBE Shop', invite: 'Invite friends', earn30: 'Earn 30 points per join', referralDesc: 'Share your referral code. When a new user joins with it and completes signup, you get 30 points automatically.', referralCode: 'Your referral code', copyInvite: 'Copy invite link',
    submitVideo: 'Submit Korean culture video', submitVideoDesc: 'Submit dance, song, drama review or culture content. Approved content can receive points after admin review.', contentCategory: 'Content category', videoTitle: 'Video title', videoUrl: 'Video URL', thumbnailUrl: 'Thumbnail image URL', shortDescription: 'Short description', submitForReview: 'Submit for review',
    dailyLearning: 'Daily Korean learning', dailyDesc: 'Start your learning journey with Korean lessons. Completed chapters are saved to your points ledger.', completeChapter: 'Complete chapter', claimFood: 'Claim K-Food purchase points', claimFoodDesc: 'Use the order ID or coupon code for manual review of your K-Food purchase.', submitClaim: 'Submit claim',
    savedProgress: 'Saved learning progress', history: 'Streaks and recent history', persistence: 'This data is loaded from your saved learning progress and sessions, so it persists after refresh.', loadingProgress: 'Loading saved progress...', trackedPaths: 'tracked paths', current: 'Current', best: 'Best', sessions: 'Sessions', totalCorrect: 'Total correct', totalPoints: 'Total points', lastCompleted: 'Last completed', notYet: 'Not yet', recentSessions: 'Recent sessions', latestCompletions: 'Latest completions', records: 'records', questions: 'questions', correct: 'correct', accuracy: 'accuracy', streak: 'Streak', noProgress: 'No saved learning progress yet. Complete a few Korean lessons and your streak history will appear here.', noSessions: 'Recent session history will appear here after you finish a learning track.',
    eventsTitle: 'Events and participation', eventsDesc: 'See upcoming K-CUBE events, understand participation requirements, RSVP directly and track points available for verified attendance.', memberEvents: 'Member events', when: 'When', where: 'Where', capacity: 'Capacity', participants: 'participants', rsvpConfirmed: 'RSVP confirmed', rsvp: 'RSVP to this event', noEvents: 'No additional published events are available right now. Check back when the admin publishes the next event.',
    myProfile: 'My profile', accountDetails: 'Account details', profileDesc: 'Update your personal information here. Email, username, points and account access stay protected.', saveChanges: 'Save changes', saving: 'Saving...', openProfile: 'Open full profile page', changePassword: 'Change password', passwordDesc: 'Use your current password to secure your account with a new one.', currentPassword: 'Current password', newPassword: 'New password (8+ characters)', confirmPassword: 'Confirm new password', updatePassword: 'Update password', updating: 'Updating...',
  },
  ko: {
    memberCommand: '회원 커맨드 센터', dashboardHeading: '문화, 학습, 음식과 쇼핑으로 포인트를 적립하세요.', dashboardIntro: 'K-CUBE는 한국 여행 순위를 향한 의미 있는 활동을 기록합니다. 한국 문화 콘텐츠를 업로드하고, 매일 학습하고, 친구를 초대하고, K-Food 구매를 등록하세요.',
    ranking: '한국 여행 순위', rankingDesc: '우승자 발표 전에 관리자가 업로드, 학습, K-Food 및 수동 조정 포인트를 확인합니다.', visitShop: 'K-CUBE 쇼핑몰 방문', invite: '친구 초대', earn30: '가입 한 명당 30포인트', referralDesc: '추천 코드를 공유하세요. 새 사용자가 코드로 가입을 완료하면 30포인트를 자동으로 받습니다.', referralCode: '추천 코드', copyInvite: '초대 링크 복사',
    submitVideo: '한국 문화 영상 제출', submitVideoDesc: '댄스, 노래, 드라마 리뷰 또는 문화 콘텐츠를 제출하세요. 관리자 검토 후 승인된 콘텐츠에 포인트가 지급될 수 있습니다.', contentCategory: '콘텐츠 카테고리', videoTitle: '영상 제목', videoUrl: '영상 URL', thumbnailUrl: '썸네일 이미지 URL', shortDescription: '간단한 설명', submitForReview: '검토를 위해 제출',
    dailyLearning: '매일 한국어 학습', dailyDesc: '한국어 레슨으로 학습 여정을 시작하세요. 완료한 챕터는 포인트 장부에 저장됩니다.', completeChapter: '챕터 완료', claimFood: 'K-Food 구매 포인트 신청', claimFoodDesc: 'K-Food 구매를 수동 검토할 수 있도록 주문 ID 또는 쿠폰 코드를 입력하세요.', submitClaim: '신청 제출',
    savedProgress: '저장된 학습 진행', history: '연속 기록 및 최근 기록', persistence: '저장된 학습 진행과 세션에서 불러온 데이터이므로 새로고침 후에도 유지됩니다.', loadingProgress: '저장된 진행을 불러오는 중...', trackedPaths: '개 학습 경로', current: '현재', best: '최고', sessions: '세션', totalCorrect: '총 정답', totalPoints: '총 포인트', lastCompleted: '마지막 완료', notYet: '아직 없음', recentSessions: '최근 세션', latestCompletions: '최근 완료', records: '개 기록', questions: '문제', correct: '정답', accuracy: '정확도', streak: '연속 기록', noProgress: '저장된 학습 진행이 아직 없습니다. 한국어 레슨을 완료하면 기록이 표시됩니다.', noSessions: '학습 트랙을 완료하면 최근 세션 기록이 여기에 표시됩니다.',
    eventsTitle: '이벤트 및 참여', eventsDesc: '예정된 K-CUBE 이벤트와 참여 조건을 확인하고 RSVP 및 인증된 참석 포인트를 관리하세요.', memberEvents: '회원 이벤트', when: '일시', where: '장소', capacity: '정원', participants: '명', rsvpConfirmed: 'RSVP 확인됨', rsvp: '이 이벤트에 RSVP', noEvents: '현재 게시된 추가 이벤트가 없습니다. 관리자가 다음 이벤트를 게시하면 다시 확인하세요.',
    myProfile: '내 프로필', accountDetails: '계정 정보', profileDesc: '여기에서 개인 정보를 업데이트하세요. 이메일, 사용자명, 포인트 및 계정 권한은 안전하게 보호됩니다.', saveChanges: '변경사항 저장', saving: '저장 중...', openProfile: '전체 프로필 열기', changePassword: '비밀번호 변경', passwordDesc: '현재 비밀번호를 사용하여 새 비밀번호로 계정을 보호하세요.', currentPassword: '현재 비밀번호', newPassword: '새 비밀번호 (8자 이상)', confirmPassword: '새 비밀번호 확인', updatePassword: '비밀번호 업데이트', updating: '업데이트 중...',
  },
  hi: {
    memberCommand: 'मेंबर कमांड सेंटर', dashboardHeading: 'कल्चर, लर्निंग, फूड और खरीदारी से पॉइंट्स कमाएँ।', dashboardIntro: 'K-CUBE आपकी Korea trip ranking के लिए meaningful activities track करता है। Korean culture content upload करें, daily learning पूरी करें, friends refer करें और K-Food purchases claim करें।',
    ranking: 'Korea trip ranking', rankingDesc: 'Winner announce होने से पहले admin uploads, learning, K-Food और manual adjustments के points verify करता है।', visitShop: 'K-CUBE Shop देखें', invite: 'दोस्तों को invite करें', earn30: 'हर join पर 30 points', referralDesc: 'अपना referral code share करें। कोई नया user code से signup पूरा करता है तो आपको 30 points अपने आप मिलेंगे।', referralCode: 'आपका referral code', copyInvite: 'Invite link copy करें',
    submitVideo: 'Korean culture video submit करें', submitVideoDesc: 'Dance, song, drama review या culture content submit करें। Admin review के बाद approved content पर points मिल सकते हैं।', contentCategory: 'Content category', videoTitle: 'Video title', videoUrl: 'Video URL', thumbnailUrl: 'Thumbnail image URL', shortDescription: 'Short description', submitForReview: 'Review के लिए submit करें',
    dailyLearning: 'Daily Korean learning', dailyDesc: 'Korean lessons के साथ learning journey शुरू करें। Completed chapters आपके points ledger में save होते हैं।', completeChapter: 'Chapter पूरा करें', claimFood: 'K-Food purchase points claim करें', claimFoodDesc: 'K-Food purchase के manual review के लिए order ID या coupon code इस्तेमाल करें।', submitClaim: 'Claim submit करें',
    savedProgress: 'Saved learning progress', history: 'Streak और recent history', persistence: 'यह data saved learning progress और sessions से load होता है, इसलिए refresh के बाद भी बना रहता है।', loadingProgress: 'Saved progress load हो रहा है...', trackedPaths: 'tracked paths', current: 'Current', best: 'Best', sessions: 'Sessions', totalCorrect: 'Total correct', totalPoints: 'Total points', lastCompleted: 'Last completed', notYet: 'अभी नहीं', recentSessions: 'Recent sessions', latestCompletions: 'Latest completions', records: 'records', questions: 'questions', correct: 'correct', accuracy: 'accuracy', streak: 'Streak', noProgress: 'अभी कोई saved learning progress नहीं है। कुछ Korean lessons पूरी करें, फिर आपकी streak history यहाँ दिखेगी।', noSessions: 'Learning track पूरा करने के बाद recent session history यहाँ दिखेगी।',
    eventsTitle: 'Events और participation', eventsDesc: 'Upcoming K-CUBE events, participation requirements, RSVP और verified attendance points देखें।', memberEvents: 'Member events', when: 'When', where: 'Where', capacity: 'Capacity', participants: 'participants', rsvpConfirmed: 'RSVP confirmed', rsvp: 'इस event के लिए RSVP करें', noEvents: 'अभी कोई additional published event उपलब्ध नहीं है। Admin के next event publish करने पर वापस देखें।',
    myProfile: 'My profile', accountDetails: 'Account details', profileDesc: 'यहाँ अपनी personal information update करें। Email, username, points और account access protected रहते हैं।', saveChanges: 'Changes save करें', saving: 'Save हो रहा है...', openProfile: 'Full profile page खोलें', changePassword: 'Password बदलें', passwordDesc: 'अपने current password की मदद से account को नए password से सुरक्षित करें।', currentPassword: 'Current password', newPassword: 'New password (8+ characters)', confirmPassword: 'Confirm new password', updatePassword: 'Password update करें', updating: 'Update हो रहा है...',
  },
};
