import type { LocalText, MenuLink } from '@/lib/kcubeContent';
import type { Language } from '@/store/useAppStore';

export interface ShopProduct {
  id: string;
  slug: string;
  title: LocalText;
  subtitle: LocalText;
  description: LocalText;
  category: LocalText;
  image: string;
  price: number;
  rewardPoints: number;
  stockLabel: LocalText;
  badges: LocalText[];
  includes: LocalText[];
}

const hindiText: Record<string, string> = {
  'Shop': 'शॉप',
  'Shop Pages': 'शॉप पेज',
  'Korean Grocery': 'कोरियन ग्रोसरी',
  'Instant Meals': 'इंस्टेंट मील्स',
  'Snacks & Drinks': 'स्नैक्स और ड्रिंक्स',
  'Ready for same-site rewards and checkout.': 'यही साइट पर रिवॉर्ड्स और चेकआउट के लिए तैयार।',
  'Low stock': 'कम स्टॉक',
  'Fast moving': 'तेज़ बिक रहा है',
  'Top seller': 'टॉप सेलर',
  'Starter pack': 'स्टार्टर पैक',
  'Limited drop': 'लिमिटेड ड्रॉप',
  'Best for first-time buyers': 'पहली बार खरीदने वालों के लिए बेस्ट',
  'Shin Ramyun Family Pack': 'शिन राम्युन फैमिली पैक',
  'Spicy Korean noodle multipack for pantry-ready quick meals.': 'जल्दी बनने वाले मील्स के लिए मसालेदार कोरियन नूडल मल्टीपैक।',
  'Six noodle packs with bold broth and pantry-friendly prep.': 'ज़बरदस्त ब्रॉथ और आसान तैयारी वाले छह नूडल पैक्स।',
  '6 ramen packs': '6 रामेन पैक',
  'Korean chili seasoning': 'कोरियन चिली सीज़निंग',
  'Reward eligible on checkout': 'चेकआउट पर रिवॉर्ड मिलेगा',
  'Bibigo Kimchi Jar': 'बिबिगो किमची जार',
  'Crunchy fermented kimchi jar for home meals, bowls and sides.': 'होम मील्स, बाउल्स और साइड्स के लिए क्रंची फर्मेंटेड किमची जार।',
  'Classic napa kimchi with balanced spice and clean tang.': 'बैलेंस्ड स्पाइस और क्लीन टैंग वाली क्लासिक नापा किमची।',
  '450g glass jar': '450g ग्लास जार',
  'Fresh cold-chain style taste': 'फ्रेश कोल्ड-चेन स्टाइल टेस्ट',
  'High reward multiplier': 'हाई रिवॉर्ड मल्टीप्लायर',
  'Tteokbokki Street Kit': 'ट्टोकबोकी स्ट्रीट किट',
  'Rice cakes, sauce and toppings for a fast Seoul street-food setup.': 'फास्ट सियोल स्ट्रीट-फूड सेटअप के लिए राइस केक्स, सॉस और टॉपिंग्स।',
  'Build a sweet-spicy tteokbokki bowl in under fifteen minutes.': 'पंद्रह मिनट से कम समय में स्वीट-स्पाइसी ट्टोकबोकी बाउल बनाएं।',
  'Rice cakes + sauce': 'राइस केक्स + सॉस',
  'Street-food style': 'स्ट्रीट-फूड स्टाइल',
  'Perfect for bundle offers': 'बंडल ऑफर के लिए परफेक्ट',
  'Korean Snack Discovery Box': 'कोरियन स्नैक डिस्कवरी बॉक्स',
  'A mixed box of chips, seaweed crisps and sweet Korean treats.': 'चिप्स, सीवीड क्रिस्प्स और स्वीट कोरियन ट्रीट्स का मिक्स बॉक्स।',
  'Try a curated snack mix designed for gifting and reward campaigns.': 'गिफ्टिंग और रिवॉर्ड कैंपेन के लिए क्यूरेटेड स्नैक मिक्स ट्राय करें।',
  '8 snack assortment': '8 स्नैक असॉर्टमेंट',
  'Great for gifting': 'गिफ्टिंग के लिए बढ़िया',
  'Signup bonus friendly': 'साइनअप बोनस के साथ अच्छा',
  'Bulgogi Marinade Duo': 'बुल्गोगी मैरिनेड डुओ',
  'Two best-selling Korean marinades for grills, bowls and meal prep.': 'ग्रिल, बाउल्स और मील प्रेप के लिए दो बेस्ट-सेलिंग कोरियन मैरिनेड्स।',
  'Sweet-savory bulgogi marinades that convert first-taste shoppers.': 'स्वीट-सेवरी बुल्गोगी मैरिनेड्स जो पहली खरीद को कन्वर्ट करें।',
  '2 bottle combo': '2 बोतल कॉम्बो',
  'Easy repeat purchase': 'आसान रिपीट खरीद',
  'Ideal cart booster': 'आदर्श कार्ट बूस्टर',
  'Korean Yuzu Sparkling Set': 'कोरियन युज़ू स्पार्कलिंग सेट',
  'Light citrus sparkling drinks for snack bundles and event hampers.': 'स्नैक बंडल्स और इवेंट हैम्पर्स के लिए हल्के साइट्रस स्पार्कलिंग ड्रिंक्स।',
  'Refreshing yuzu cans made for bundles, hampers and quick checkout wins.': 'बंडल्स, हैम्पर्स और तेज़ चेकआउट जीत के लिए रिफ्रेशिंग युज़ू कैन्स।',
  '4 can bundle': '4 कैन बंडल',
  'Festival-ready item': 'फेस्टिवल रेडी आइटम',
  'Cart closeer': 'कार्ट क्लोजर',
  'Earn rewards when your order is completed on K-CUBE.': 'K-CUBE पर ऑर्डर पूरा होने पर रिवॉर्ड कमाएं।',
  'Add to cart': 'कार्ट में जोड़ें',
  'Buy now': 'अभी खरीदें',
  'Sign in to buy': 'खरीदने के लिए साइन इन करें',
};

const txt = (en: string, ko: string, hi: string): LocalText => ({ en, ko, hi: hindiText[en] ?? hi });

export const shopCopy: Record<Language, Record<string, string>> = {
  en: {
    badge: 'K-CUBE Shop',
    title: 'Buy Korean products directly on K-CUBE and earn rewards on every completed order',
    subtitle: 'Browse pantry staples, snacks, kits and bundles without leaving the ecosystem. Sign up rewards, checkout rewards and product discovery all stay on this site.',
    cart: 'Cart summary',
    checkout: 'Complete order',
    empty: 'Your cart is empty. Add a few Korean favorites to start checkout.',
    loginGate: 'Sign in or create an account before checkout to unlock signup rewards and product purchase rewards.',
    rewardsLine: 'Earn rewards when your order is completed on K-CUBE.',
    addToCart: 'Add to cart',
    buyNow: 'Buy now',
    signInToBuy: 'Sign in to buy',
    continueShopping: 'Continue shopping',
    viewDetails: 'View details',
    orderPlaced: 'Order placed on K-CUBE. Rewards have been added to the member wallet.',
    qty: 'Qty',
    orderRewards: 'Order rewards',
    accountPrompt: 'Create account and unlock your welcome bonus plus purchase rewards.',
    shopCategory: 'Shop',
  },
  ko: {
    badge: 'K-CUBE ìƒµ',
    title: 'K-CUBEì—ì„œ ì§ì ‘ í•œêµ­ ì œí’ˆì„ êµ¬ë§¤í•˜ê³  ì™„ë£Œëœ ì£¼ë¬¸ë§ˆë‹¤ ë³´ìƒì„ ë°›ìœ¼ì„¸ìš”.',
    subtitle: 'íŒ¬íŠ¸ë¦¬ í•„ìˆ˜í’ˆ, ìŠ¤ë‚µ, í‚·, ë²ˆë“¤ì„ ìƒíƒœê³„ë¥¼ ë– ë‚˜ì§€ ì•Šê³  ë° ìž¥ë°”êµ¬ë‹ˆì— ë‹´ìœ¼ì„¸ìš”. íšŒì›ê°€ìž… ë³´ìƒ, ê²°ì œ ë³´ìƒ, ìƒí’ˆ íƒìƒ‰ì´ ëª¨ë‘ ì´ ì‚¬ì´íŠ¸ì— ë‚¨ìŠµë‹ˆë‹¤.',
    cart: 'ìž¥ë°”êµ¬ë‹ˆ ìš”ì•½',
    checkout: 'ì£¼ë¬¸ ì™„ë£Œ',
    empty: 'ìž¥ë°”êµ¬ë‹ˆê°€ ë¹„ì–´ ìžˆìŠµë‹ˆë‹¤. ê²°ì œë¥¼ ì‹œìž‘í•˜ë ¤ë©´ ì œí’ˆì„ ë‹´ìœ¼ì„¸ìš”.',
    loginGate: 'ê²°ì œ ì „ ë¡œê·¸ì¸ ë˜ëŠ” íšŒì›ê°€ìž…ì„ í•˜ê³  ì‹ ê·œ íšŒì› ë³´ìƒê³¼ êµ¬ë§¤ ë³´ìƒì„ í™œì„±í™”í•˜ì„¸ìš”.',
    rewardsLine: 'K-CUBEì—ì„œ ì£¼ë¬¸ì´ ì™„ë£Œë˜ë©´ ë³´ìƒì„ ì ë¦½í•©ë‹ˆë‹¤.',
    addToCart: 'ìž¥ë°”êµ¬ë‹ˆ ë‹´ê¸°',
    buyNow: 'ë°”ë¡œ êµ¬ë§¤',
    signInToBuy: 'ë¡œê·¸ì¸ í›„ êµ¬ë§¤',
    continueShopping: 'ê³„ì† ì‡¼í•‘',
    viewDetails: 'ìƒì„¸ ë³´ê¸°',
    orderPlaced: 'K-CUBEì—ì„œ ì£¼ë¬¸ì´ ì™„ë£Œë˜ì—ˆìŠµë‹ˆë‹¤. ë³´ìƒì´ ë©¤ë²„ ì§€ê°‘ì— ì¶”ê°€ë˜ì—ˆìŠµë‹ˆë‹¤.',
    qty: 'ìˆ˜ëŸ‰',
    orderRewards: 'ì£¼ë¬¸ ë³´ìƒ',
    accountPrompt: 'ê³„ì •ì„ ë§Œë“¤ê³  í™˜ì˜ ë³´ë„ˆìŠ¤ì™€ êµ¬ë§¤ ë³´ìƒì„ ë°›ìœ¼ì„¸ìš”.',
    shopCategory: 'ìƒµ',
  },
  hi: {
    badge: 'K-CUBE Shop',
    title: 'K-CUBE par seedha Korean products buy karo aur har completed order par rewards pao',
    subtitle: 'Pantry staples, snacks, kits aur bundles ko bina site chhode browse karo. Signup rewards, checkout rewards aur product discovery sab isi site par rahega.',
    cart: 'Cart summary',
    checkout: 'Complete order',
    empty: 'Aapka cart abhi empty hai. Checkout start karne ke liye kuch products add karein.',
    loginGate: 'Checkout se pehle sign in ya account create karein taaki signup rewards aur purchase rewards unlock ho sakein.',
    rewardsLine: 'K-CUBE par order complete hone par rewards milenge.',
    addToCart: 'Add to cart',
    buyNow: 'Buy now',
    signInToBuy: 'Sign in to buy',
    continueShopping: 'Continue shopping',
    viewDetails: 'View details',
    orderPlaced: 'Order K-CUBE par place ho gaya. Rewards member wallet me add ho gaye hain.',
    qty: 'Qty',
    orderRewards: 'Order rewards',
    accountPrompt: 'Account create karke welcome bonus aur purchase rewards unlock karein.',
    shopCategory: 'Shop',
  },
};

export const shopProducts: ShopProduct[] = [
  {
    id: 'shin-ramyun-family-pack',
    slug: 'shin-ramyun-family-pack',
    title: txt('Shin Ramyun Family Pack', 'ì‹  ë¼ë©´ íŒ¨ë°€ë¦¬ íŒ©', 'Shin Ramyun Family Pack'),
    subtitle: txt('Spicy Korean noodle multipack for pantry-ready quick meals.', 'íŒ¬íŠ¸ë¦¬ìš© ìŠ¤íŒŒì´ì‹œ í•œêµ­ ë¼ë©´ ë©€í‹°íŒ©.', 'Spicy Korean noodle multipack for pantry-ready quick meals.'),
    description: txt('Six noodle packs with bold broth and pantry-friendly prep.', 'ê°•í•œ êµ­ë¬¼ ë§›ê³¼ ì‰¬ìš´ ì¡°ë¦¬ê°€ ìž¥ì ì¸ 6ê°œ ì„¸íŠ¸ìž…ë‹ˆë‹¤.', 'Six noodle packs with bold broth and pantry-friendly prep.'),
    category: txt('Instant Meals', 'ì¦‰ì„ì‹í’ˆ', 'Instant Meals'),
    image: 'https://images.unsplash.com/photo-1515003197210-e0cd71810b5f?auto=format&fit=crop&w=1200&q=80',
    price: 699,
    rewardPoints: 70,
    stockLabel: txt('Fast moving', 'ë¹ ë¥´ê²Œ íŒë§¤ ì¤‘', 'Fast moving'),
    badges: [txt('Top seller', 'ìƒìœ„ íŒë§¤', 'Top seller'), txt('Starter pack', 'ìŠ¤íƒ€í„° íŒ©', 'Starter pack')],
    includes: [txt('6 ramen packs', 'ë¼ë©´ 6ê°œ', '6 ramen packs'), txt('Korean chili seasoning', 'í•œêµ­ ê³ ì¶” ì‹œì¦Œë‹', 'Korean chili seasoning'), txt('Reward eligible on checkout', 'ê²°ì œ ë³´ìƒ ì ìš©', 'Reward eligible on checkout')],
  },
  {
    id: 'bibigo-kimchi-jar',
    slug: 'bibigo-kimchi-jar',
    title: txt('Bibigo Kimchi Jar', 'ë¹„ë¹„ê³  ê¹€ì¹˜ ìž', 'Bibigo Kimchi Jar'),
    subtitle: txt('Crunchy fermented kimchi jar for home meals, bowls and sides.', 'ì§‘ë°¥ê³¼ ì‚¬ì´ë“œì— ì–´ìš¸ë¦¬ëŠ” ì•„ì‚­í•œ ë°œíš¨ ê¹€ì¹˜ìž…ë‹ˆë‹¤.', 'Crunchy fermented kimchi jar for home meals, bowls and sides.'),
    description: txt('Classic napa kimchi with balanced spice and clean tang.', 'ê· í˜• ìž¡ížŒ ë§¤ì½¤í•¨ê³¼ ê¹”ë”í•œ ì‹ ë§›ì˜ í´ëž˜ì‹ ë°°ì¶” ê¹€ì¹˜.', 'Classic napa kimchi with balanced spice and clean tang.'),
    category: txt('Korean Grocery', 'í•œêµ­ ì‹ë£Œí’ˆ', 'Korean Grocery'),
    image: 'https://images.unsplash.com/photo-1607301405390-d831c242f59b?auto=format&fit=crop&w=1200&q=80',
    price: 549,
    rewardPoints: 55,
    stockLabel: txt('Top seller', 'ìƒìœ„ íŒë§¤', 'Top seller'),
    badges: [txt('Low stock', 'ìž¬ê³  ë¶€ì¡±', 'Low stock'), txt('Best for first-time buyers', 'ì²« êµ¬ë§¤ìž ì¶”ì²œ', 'Best for first-time buyers')],
    includes: [txt('450g glass jar', '450g ìœ ë¦¬ë³‘', '450g glass jar'), txt('Fresh cold-chain style taste', 'ì‹ ì„ í•œ ë§›', 'Fresh cold-chain style taste'), txt('High reward multiplier', 'ë†’ì€ ë³´ìƒ ë¹„ìœ¨', 'High reward multiplier')],
  },
  {
    id: 'tteokbokki-street-kit',
    slug: 'tteokbokki-street-kit',
    title: txt('Tteokbokki Street Kit', 'ë–¡ë³¶ì´ ìŠ¤íŠ¸ë¦¬íŠ¸ í‚·', 'Tteokbokki Street Kit'),
    subtitle: txt('Rice cakes, sauce and toppings for a fast Seoul street-food setup.', 'ì„œìš¸ ë¶„ì‹ ê°ì„±ì„ ìœ„í•œ ë–¡, ì†ŒìŠ¤, í† í•‘ í‚·.', 'Rice cakes, sauce and toppings for a fast Seoul street-food setup.'),
    description: txt('Build a sweet-spicy tteokbokki bowl in under fifteen minutes.', '15ë¶„ ì•ˆì— ë‹¬ì½¤ë§¤ì½¤í•œ ë–¡ë³¶ì´ë¥¼ ë§Œë“œëŠ” ì„¸íŠ¸.', 'Build a sweet-spicy tteokbokki bowl in under fifteen minutes.'),
    category: txt('Instant Meals', 'ì¦‰ì„ì‹í’ˆ', 'Instant Meals'),
    image: 'https://images.unsplash.com/photo-1583224964978-2f4f7aaf4230?auto=format&fit=crop&w=1200&q=80',
    price: 799,
    rewardPoints: 85,
    stockLabel: txt('Limited drop', 'í•œì • ì¶œì‹œ', 'Limited drop'),
    badges: [txt('Street-food style', 'ê¸¸ê±°ë¦¬ ìŠ¤íƒ€ì¼', 'Street-food style')],
    includes: [txt('Rice cakes + sauce', 'ë–¡ + ì†ŒìŠ¤', 'Rice cakes + sauce'), txt('Street-food style', 'ê¸¸ê±°ë¦¬ ìŠ¤íƒ€ì¼', 'Street-food style'), txt('Perfect for bundle offers', 'ë²ˆë“¤ ì˜¤í¼ ì í•©', 'Perfect for bundle offers')],
  },
  {
    id: 'korean-snack-discovery-box',
    slug: 'korean-snack-discovery-box',
    title: txt('Korean Snack Discovery Box', 'í•œêµ­ ìŠ¤ë‚µ ë””ìŠ¤ì»¤ë²„ë¦¬ ë°•ìŠ¤', 'Korean Snack Discovery Box'),
    subtitle: txt('A mixed box of chips, seaweed crisps and sweet Korean treats.', 'ì¹©, ê¹€ ìŠ¤ë‚µ, ë‹¬ì½¤í•œ ê°„ì‹ì„ ë‹´ì€ ë¯¹ìŠ¤ ë°•ìŠ¤.', 'A mixed box of chips, seaweed crisps and sweet Korean treats.'),
    description: txt('Try a curated snack mix designed for gifting and reward campaigns.', 'ì„ ë¬¼ê³¼ ë³´ìƒ ìº íŽ˜ì¸ì— ì–´ìš¸ë¦¬ëŠ” ìŠ¤ë‚µ ë¯¹ìŠ¤.', 'Try a curated snack mix designed for gifting and reward campaigns.'),
    category: txt('Snacks & Drinks', 'ìŠ¤ë‚µ & ìŒë£Œ', 'Snacks & Drinks'),
    image: 'https://images.unsplash.com/photo-1576618148400-f54bed99fcfd?auto=format&fit=crop&w=1200&q=80',
    price: 1199,
    rewardPoints: 120,
    stockLabel: txt('Top seller', 'ìƒìœ„ íŒë§¤', 'Top seller'),
    badges: [txt('Great for gifting', 'ì„ ë¬¼ ì¶”ì²œ', 'Great for gifting'), txt('Signup bonus friendly', 'ì‹ ê·œ íšŒì› ì¶”ì²œ', 'Signup bonus friendly')],
    includes: [txt('8 snack assortment', '8ê°œ ìŠ¤ë‚µ êµ¬ì„±', '8 snack assortment'), txt('Great for gifting', 'ì„ ë¬¼ ì¶”ì²œ', 'Great for gifting'), txt('Reward eligible on checkout', 'ê²°ì œ ë³´ìƒ ì ìš©', 'Reward eligible on checkout')],
  },
  {
    id: 'bulgogi-marinade-duo',
    slug: 'bulgogi-marinade-duo',
    title: txt('Bulgogi Marinade Duo', 'ë¶ˆê³ ê¸° ë§ˆë¦¬ë„¤ì´ë“œ ë“€ì˜¤', 'Bulgogi Marinade Duo'),
    subtitle: txt('Two best-selling Korean marinades for grills, bowls and meal prep.', 'ê·¸ë¦´ê³¼ ë°¥, ë°€í”„ë ™ì ì–´ìš¸ë¦¬ëŠ” ì¸ê¸° ì–‘ë… ë‘ ë³‘.', 'Two best-selling Korean marinades for grills, bowls and meal prep.'),
    description: txt('Sweet-savory bulgogi marinades that convert first-taste shoppers.', 'ì²« êµ¬ë§¤ìžì—ê²Œë„ ë§¤ë ¥ì ì¸ ë‹¬ì§€ë§Œ ê°ì¹ ë§› ìžˆëŠ” ë¶ˆê³ ê¸° ì–‘ë….', 'Sweet-savory bulgogi marinades that convert first-taste shoppers.'),
    category: txt('Korean Grocery', 'í•œêµ­ ì‹ë£Œí’ˆ', 'Korean Grocery'),
    image: 'https://images.unsplash.com/photo-1473093295043-cdd812d0e601?auto=format&fit=crop&w=1200&q=80',
    price: 899,
    rewardPoints: 95,
    stockLabel: txt('Fast moving', 'ë¹ ë¥´ê²Œ íŒë§¤ ì¤‘', 'Fast moving'),
    badges: [txt('Ideal cart booster', 'ìž¥ë°”êµ¬ë‹ˆ ì¶”ê°€ ì¶”ì²œ', 'Ideal cart booster')],
    includes: [txt('2 bottle combo', '2ë³‘ ì½¤ë³´', '2 bottle combo'), txt('Easy repeat purchase', 'ë°˜ë³µ êµ¬ë§¤ ì‰¬ì›€', 'Easy repeat purchase'), txt('Reward eligible on checkout', 'ê²°ì œ ë³´ìƒ ì ìš©', 'Reward eligible on checkout')],
  },
  {
    id: 'korean-yuzu-sparkling-set',
    slug: 'korean-yuzu-sparkling-set',
    title: txt('Korean Yuzu Sparkling Set', 'í•œêµ­ ìœ ìž ìŠ¤íŒŒí´ë§ ì„¸íŠ¸', 'Korean Yuzu Sparkling Set'),
    subtitle: txt('Light citrus sparkling drinks for snack bundles and event hampers.', 'ìŠ¤ë‚µ ë²ˆë“¤ê³¼ ì´ë²¤íŠ¸ í–„í¼ì— ì–´ìš¸ë¦¬ëŠ” ì‹±ê·¸ëŸ¬ìš´ ìŒë£Œ.', 'Light citrus sparkling drinks for snack bundles and event hampers.'),
    description: txt('Refreshing yuzu cans made for bundles, hampers and quick checkout wins.', 'ë²ˆë“¤ê³¼ í–„í¼, ë¹ ë¥¸ ê²°ì œì— ì–´ìš¸ë¦¬ëŠ” ìƒí¼í•œ ìœ ìž ìº” ì„¸íŠ¸.', 'Refreshing yuzu cans made for bundles, hampers and quick checkout wins.'),
    category: txt('Snacks & Drinks', 'ìŠ¤ë‚µ & ìŒë£Œ', 'Snacks & Drinks'),
    image: 'https://images.unsplash.com/photo-1544145945-f90425340c7e?auto=format&fit=crop&w=1200&q=80',
    price: 649,
    rewardPoints: 60,
    stockLabel: txt('Fast moving', 'ë¹ ë¥´ê²Œ íŒë§¤ ì¤‘', 'Fast moving'),
    badges: [txt('Festival-ready item', 'íŽ˜ìŠ¤í‹°ë²Œ ì¶”ì²œ', 'Festival-ready item')],
    includes: [txt('4 can bundle', '4ìº” ë²ˆë“¤', '4 can bundle'), txt('Festival-ready item', 'íŽ˜ìŠ¤í‹°ë²Œ ì¶”ì²œ', 'Festival-ready item'), txt('Reward eligible on checkout', 'ê²°ì œ ë³´ìƒ ì ìš©', 'Reward eligible on checkout')],
  },
];

export const findShopProduct = (slug: string) => shopProducts.find((item) => item.slug === slug);

export const shopMenuLinks: MenuLink[] = shopProducts.map((product) => ({
  label: product.title,
  href: `/shop/${product.slug}`,
  description: product.subtitle,
  points: product.rewardPoints,
  children: product.includes.map((item) => ({
    label: item,
    href: `/shop/${product.slug}`,
    description: product.description,
    points: product.rewardPoints,
  })),
}));
